### PR TITLE
modify delete to allow for response body

### LINKED ISSUE #33: DELETE doesn't allow for response body
_From @Fuuzetsu on March 25, 2015 0:16_

I have an API here that I DELETE to and which returns 200 (so we get `Left "HTTP DELETE request failed with status: 200 - OK"`, another issue) and some body which we can not process because unlike `Put` or `Post`, we can't parametrise the `Delete`.

_Copied from original issue: haskell-servant/servant-client#19_

### PR DESCRIPTION
**Pull request by codedmart**
@alpmestan @jkarni This could use a good check over just to be sure I got this right. Please let me know if I missed anything or did something wrong. All tests are passing in servant, servant-client, servant-docs, servant-jquery, and servant-server. Fixes #33.

### CODE REVIEW

File: servant-docs/example/greet.hs [hunk 1]
```diff
@@ -53,6 +53,14 @@ instance ToParam (MatrixParam "lang" String) where
                   "Get the greeting message selected language. Default is en."
                   Normal
 
+instance ToSample () Greet where
```
Comment (jkarni) [inline servant-docs/example/greet.hs]: I don't think this is doing the right thing. `ToSample` should pretty much always have it's first and second arguments the same (there is only one exception, `Headers ls a`, which is kind of sticking out like a sore thumb right now and caused us to add the second param in the first place). In essence, the first argument is what this is a sample for, and the second is what the type of the sample is (this might need to be better documented -- sorry). So in this case, you probably want `ToSample () ()`, or *maybe* another special case, `ToSample () String` with toSample ~~ "NO CONTENT".

**Comment by jkarni** [comment]
This is great! I was feeling pretty bad about releasing with fixing #33... Could you add entries to the changelogs of all the repos this touches?

File: servant-docs/example/greet.hs (hunk 1 above)
Comment (codedmart) [inline servant-docs/example/greet.hs]: Yeah this part seemed wrong to me. I will try your suggestion for now.

**Comment by codedmart** [comment]
I will update the change logs and update this pr. Thanks!

**Comment by codedmart** [comment]
All updated and tests are passing. Let me know if I can do anything else.

**Comment by jkarni** [comment]
Thanks again.
